# Generated by Django 4.2.10 on 2024-02-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='title',
            field=models.CharField(default='Nestify', max_length=100),
        ),
    ]
